const defaultProducts=[
{id:1,name:"Mango Passion Juice",cat:"Juice",price:5000,image:"https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=800&q=80",desc:"Fresh mango + passion fruit blend."},
{id:2,name:"Strawberry Yoghurt",cat:"Yoghurt",price:6000,image:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",desc:"Creamy yoghurt with strawberry."},
{id:3,name:"Green Detox",cat:"Detox",price:6500,image:"https://images.unsplash.com/photo-1610970881699-44a5587cabec?auto=format&fit=crop&w=800&q=80",desc:"A refreshing green fruit & veg detox."},
{id:4,name:"Tropical Smoothie",cat:"Smoothie",price:7000,image:"https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",desc:"Banana, pineapple and creamy goodness."},
{id:5,name:"Watermelon Cooler",cat:"Juice",price:4500,image:"https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=800&q=80",desc:"Cold, fresh watermelon juice."},
{id:6,name:"Vanilla Yoghurt Cup",cat:"Yoghurt",price:5500,image:"https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=800&q=80",desc:"Smooth vanilla yoghurt, made fresh."},
{id:7,name:"Pineapple Detox",cat:"Detox",price:6000,image:"https://images.unsplash.com/photo-1622597467836-f3285f2131b8?auto=format&fit=crop&w=800&q=80",desc:"Pineapple, ginger and citrus."},
{id:8,name:"Berry Power Smoothie",cat:"Smoothie",price:7500,image:"https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=800&q=80",desc:"Berry-rich smoothie for a bright start."}
];
let products=JSON.parse(localStorage.getItem("my_products")||"null")||defaultProducts;
let cart=JSON.parse(localStorage.getItem("my_cart")||"[]");
let orders=JSON.parse(localStorage.getItem("my_orders")||"[]");
let users=JSON.parse(localStorage.getItem("my_users")||"[]");
let currentUser=JSON.parse(localStorage.getItem("my_current")||"null");
let admin=false, currentCat="All";

const money=n=>"TZS "+Number(n).toLocaleString();
const save=()=>{localStorage.setItem("my_products",JSON.stringify(products));localStorage.setItem("my_cart",JSON.stringify(cart));localStorage.setItem("my_orders",JSON.stringify(orders));localStorage.setItem("my_users",JSON.stringify(users));localStorage.setItem("my_current",JSON.stringify(currentUser));};
const toast=m=>{let t=document.getElementById("toast");t.textContent=m;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2600)};
function showPage(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="menu")renderMenu();if(id==="cart")renderCart();if(id==="orders")renderOrders();if(id==="account")renderAccount();if(id==="admin")renderAdmin();window.scrollTo({top:0,behavior:"smooth"})}
function filterCat(cat,el){currentCat=cat;document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));el.classList.add("active");renderMenu()}
function renderMenu(){let q=(document.getElementById("search")?.value||"").toLowerCase();let list=products.filter(p=>(currentCat==="All"||p.cat===currentCat)&&(`${p.name} ${p.desc}`.toLowerCase().includes(q)));document.getElementById("productGrid").innerHTML=list.map(p=>`<article class="product"><img src="${p.image}" alt="${p.name}" onerror="this.src='https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80'"><div class="product-body"><span class="tag">${p.cat}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="price">${money(p.price)}</div><button class="add" onclick="addToCart(${p.id})">Add to order +</button></div></article>`).join("")||`<div class="empty">No drinks found.</div>`}
function addToCart(id){let x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();updateCartCount();toast("Added to your order 🥭");}
function updateCartCount(){document.getElementById("cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function renderCart(){let box=document.getElementById("cartItems");let empty=document.getElementById("cartEmpty");if(!cart.length){box.innerHTML="";empty.classList.remove("hidden");document.getElementById("cartTotal").textContent=money(0);return}empty.classList.add("hidden");let total=0;box.innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);if(!p)return "";total+=p.price*i.qty;return `<div class="cart-row"><img src="${p.image}"><div><b>${p.name}</b><div class="muted">${money(p.price)} each</div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><span>${i.qty}</span><button onclick="changeQty(${p.id},1)">+</button></div></div><div><b>${money(p.price*i.qty)}</b><br><button class="remove" onclick="removeCart(${p.id})">Remove</button></div></div>`}).join("");document.getElementById("cartTotal").textContent=money(total);document.getElementById("loginHint").classList.toggle("hidden",!!currentUser);if(currentUser){document.getElementById("orderName").value=currentUser.name;document.getElementById("orderPhone").value=currentUser.phone}}
function changeQty(id,d){let x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save();renderCart();updateCartCount()}
function removeCart(id){cart=cart.filter(i=>i.id!==id);save();renderCart();updateCartCount()}
document.getElementById("payment").onchange=e=>{document.getElementById("lipanote").classList.toggle("hidden",e.target.value!=="Lipa Namba");document.getElementById("refWrap").classList.toggle("hidden",e.target.value!=="Lipa Namba")};
function placeOrder(){if(!currentUser){toast("Please register or login first.");showPage("account");return}if(!cart.length){toast("Your cart is empty.");return}let location=document.getElementById("orderLocation").value.trim();if(!location){toast("Please enter your delivery location.");return}let payment=document.getElementById("payment").value;if(payment==="Lipa Namba"&&!document.getElementById("paymentRef").value.trim()){toast("Enter your payment reference.");return}let total=cart.reduce((s,i)=>s+(products.find(p=>p.id===i.id)?.price||0)*i.qty,0);let o={id:"MY"+Date.now().toString().slice(-8),userId:currentUser.id,customer:currentUser.name,phone:currentUser.phone,items:cart.map(i=>{let p=products.find(x=>x.id===i.id);return {name:p.name,qty:i.qty,price:p.price}}),total,location,note:document.getElementById("orderNote").value,payment,paymentRef:document.getElementById("paymentRef").value,status:"Received",driver:null,created:new Date().toISOString()};orders.unshift(o);cart=[];save();renderCart();updateCartCount();toast("Order received successfully 🎉");showPage("orders")}
function renderOrders(){let list=orders.filter(o=>currentUser&&o.userId===currentUser.id);document.getElementById("ordersList").innerHTML=currentUser?(list.length?list.map(o=>orderCard(o,false)).join(""):`<div class="panel empty">No orders yet. Your next fresh drink is waiting 🥭</div>`):`<div class="panel empty">Login to see your orders.</div>`}
function orderCard(o,adm){let items=o.items.map(i=>`${i.name} × ${i.qty}`).join(", ");return `<div class="order-card"><div style="display:flex;justify-content:space-between;gap:10px"><div><b>${o.id}</b><div class="muted">${new Date(o.created).toLocaleString()}</div></div><span class="status ${o.status.toLowerCase().replaceAll(" ","-")}">${o.status}</span></div><p><b>Items:</b> ${items}</p><p><b>Total:</b> ${money(o.total)} · <b>Payment:</b> ${o.payment}</p><p><b>Destination:</b> ${o.location}</p>${o.driver?`<div class="driver-box">🚚 <b>Driver assigned:</b> ${o.driver.name}<br>📞 ${o.driver.phone}</div>`:""}${adm?`<div class="order-actions"><select onchange="setStatus('${o.id}',this.value)"><option ${o.status==="Received"?"selected":""}>Received</option><option ${o.status==="Preparing"?"selected":""}>Preparing</option><option ${o.status==="Out for delivery"?"selected":""}>Out for delivery</option><option ${o.status==="Delivered"?"selected":""}>Delivered</option></select><input id="dn-${o.id}" placeholder="Driver name"><input id="dp-${o.id}" placeholder="Driver phone"><button class="btn small" onclick="assignDriver('${o.id}')">Assign driver</button><button class="btn small" onclick="notifyCustomer('${o.id}')">WhatsApp customer</button></div>`:""}</div>`}
function authTab(mode,el){document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));el.classList.add("active");let reg=mode==="register";document.getElementById("confirmWrap").classList.toggle("hidden",!reg);document.getElementById("authName").required=reg;document.getElementById("accountTitle").textContent=reg?"Create your Mr. Yoghurt account":"Welcome back";document.getElementById("authSubmit").textContent=reg?"Create account":"Login";document.getElementById("authForm").dataset.mode=mode}
document.getElementById("authForm").dataset.mode="login";
function handleAuth(e){e.preventDefault();let mode=e.target.dataset.mode,name=authName.value.trim(),phone=authPhone.value.trim(),email=authEmail.value.trim(),pass=authPass.value;if(mode==="register"){if(pass!==authConfirm.value){toast("Passwords do not match.");return}if(users.some(u=>u.phone===phone)){toast("This phone is already registered.");return}let u={id:"U"+Date.now(),name,phone,email,password:pass};users.push(u);currentUser=u;toast("Account created successfully 🎉")}else{let u=users.find(x=>x.phone===phone&&x.password===pass);if(!u){toast("Invalid phone or password.");return}currentUser=u;toast("Welcome back, "+u.name+" 👋")}save();renderAccount();renderCart();showPage("menu")}
function renderAccount(){document.getElementById("profileName").textContent=currentUser?.name||"Not logged in";document.getElementById("profilePhone").textContent=currentUser?currentUser.phone:"Create/login to manage orders.";document.getElementById("avatar").textContent=currentUser?.name?.[0]?.toUpperCase()||"?";}
function logout(){currentUser=null;save();renderAccount();toast("Logged out.");showPage("home")}
function adminLogin(){if(adminUser.value==="admin"&&adminPass.value==="MrYoghurt@2026"){admin=true;renderAdmin();toast("Admin dashboard unlocked.");}else toast("Wrong admin credentials.");}
function adminLogout(){admin=false;renderAdmin()}
function renderAdmin(){document.getElementById("adminLogin").classList.toggle("hidden",admin);document.getElementById("adminDash").classList.toggle("hidden",!admin);if(!admin)return;document.getElementById("statOrders").textContent=orders.length;document.getElementById("statCustomers").textContent=users.length;document.getElementById("statSales").textContent=money(orders.reduce((s,o)=>s+o.total,0));document.getElementById("statProducts").textContent=products.length;document.getElementById("adminProducts").innerHTML=products.map(p=>`<div class="admin-item"><img src="${p.image}"><div><b>${p.name}</b><small class="muted">${p.cat} · ${money(p.price)}</small></div><div><button class="btn small" onclick="editProduct(${p.id})">Edit</button><button class="btn small" onclick="deleteProduct(${p.id})">Delete</button></div></div>`).join("");document.getElementById("adminOrders").innerHTML=orders.length?orders.map(o=>orderCard(o,true)).join(""):`<div class="empty">No orders yet.</div>`}
function saveProduct(){let id=editId.value?Number(editId.value):Date.now();let p={id,name:pName.value.trim(),cat:pCat.value,price:Number(pPrice.value),image:pImage.value.trim()||"https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80",desc:pDesc.value.trim()||"Freshly prepared by Mr. Yoghurt."};if(!p.name||!p.price){toast("Name and price are required.");return}let idx=products.findIndex(x=>x.id===id);if(idx>=0)products[idx]=p;else products.push(p);save();clearProductForm();renderAdmin();renderMenu();toast("Drink saved.");}
function editProduct(id){let p=products.find(x=>x.id===id);editId.value=p.id;pName.value=p.name;pCat.value=p.cat;pPrice.value=p.price;pImage.value=p.image;pDesc.value=p.desc;window.scrollTo({top:0,behavior:"smooth"})}
function clearProductForm(){editId.value="";pName.value="";pPrice.value="";pImage.value="";pDesc.value=""}
function deleteProduct(id){if(confirm("Delete this drink?")){products=products.filter(p=>p.id!==id);save();renderAdmin();renderMenu();toast("Drink deleted.")}}
function setStatus(id,status){let o=orders.find(x=>x.id===id);if(o){o.status=status;save();renderAdmin();toast("Order updated.");}}
function assignDriver(id){let o=orders.find(x=>x.id===id),name=document.getElementById("dn-"+id).value.trim(),phone=document.getElementById("dp-"+id).value.trim();if(!name||!phone){toast("Enter driver name and phone.");return}o.driver={name,phone};o.status="Out for delivery";save();renderAdmin();toast("Driver assigned and customer can see the details.")}
function notifyCustomer(id){let o=orders.find(x=>x.id===id);if(!o)return;let text=`Mr. Yoghurt order ${o.id}: your order has been ${o.status}.${o.driver?` Driver: ${o.driver.name}, ${o.driver.phone}.`:""} Total: ${money(o.total)}.`;window.open("https://wa.me/"+o.phone.replace(/\D/g,"")+"?text="+encodeURIComponent(text),"_blank")}
function exportOrders(){let blob=new Blob([JSON.stringify(orders,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mr-yoghurt-orders.json";a.click();URL.revokeObjectURL(a.href)}
function whatsappOrder(){let items=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `${p.name} x${i.qty}`}).join(", ");let msg=`Hello Mr. Yoghurt, I want to order: ${items||"a drink"}. Please assist me.`;window.open("https://wa.me/255676475401?text="+encodeURIComponent(msg),"_blank")}
function openAssistant(){document.getElementById("assistant").classList.remove("hidden")}
function closeAssistant(){document.getElementById("assistant").classList.add("hidden")}
function sendChat(){let input=document.getElementById("chatInput"),q=input.value.trim();if(!q)return;let log=document.getElementById("chatLog");log.innerHTML+=`<div class="user-msg">${q}</div>`;let l=q.toLowerCase(),reply;if(l.includes("detox"))reply="Try our Green Detox or Pineapple Detox. If you want a lighter option, ask for a recommendation based on your goal.";else if(l.includes("smooth"))reply="Our Tropical Smoothie and Berry Power Smoothie are creamy, fruity choices.";else if(l.includes("yoghurt")||l.includes("yogurt"))reply="Strawberry Yoghurt is a customer-friendly favourite; Vanilla Yoghurt Cup is a milder option.";else if(l.includes("price")||l.includes("bei"))reply="You can see live prices on the Menu. Admin can update prices anytime.";else if(l.includes("delivery")||l.includes("location"))reply="Add your destination in Checkout. The admin can assign a driver and the driver name/phone will appear in your order tracking.";else if(l.includes("payment")||l.includes("lipa"))reply="Choose Lipa Namba at Checkout and enter your payment transaction reference. For a real online payment gateway, connect a server-side payment provider before production.";else if(l.includes("human")||l.includes("help")||l.includes("customer"))reply="Customer service: 0697983933. Orders/WhatsApp: 0676475401.";else reply="I can help with juices, yoghurt, detox, smoothies, prices, delivery, payments and order tracking. What would you like?";setTimeout(()=>{log.innerHTML+=`<div class="bot">${reply}</div>`;log.scrollTop=log.scrollHeight},250);input.value=""}
renderMenu();renderCart();renderAccount();updateCartCount();
